// src/FamilyHub.Web/src/components/MedicationsTab.tsx
import { useEffect, useState, type FormEvent } from 'react'
import {
  ApiError,
  createMedication,
  deleteMedication,
  getMedications,
  updateMedication,
} from '../api'
import type { Medication } from '../types'

interface Props {
  familyId: string
}

const emptyForm = { name: '', instructions: '', expiryDate: '', quantity: 1 }

export default function MedicationsTab({ familyId }: Props) {
  const [items, setItems] = useState<Medication[]>([])
  const [form, setForm] = useState(emptyForm)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function refresh() {
    try {
      setItems(await getMedications(familyId))
      setError(null)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось загрузить аптечку.')
    }
  }

  useEffect(() => {
    refresh()
    setForm(emptyForm)
    setEditingId(null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [familyId])

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (!form.name.trim()) return
    const input = {
      name: form.name.trim(),
      instructions: form.instructions.trim() || null,
      expiryDate: form.expiryDate || null,
      quantity: Number(form.quantity) || 0,
    }
    try {
      if (editingId) {
        await updateMedication(editingId, input)
      } else {
        await createMedication(familyId, input)
      }
      setForm(emptyForm)
      setEditingId(null)
      await refresh()
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось сохранить запись.')
    }
  }

  function startEdit(item: Medication) {
    setEditingId(item.id)
    setForm({
      name: item.name,
      instructions: item.instructions ?? '',
      expiryDate: item.expiryDate ?? '',
      quantity: item.quantity,
    })
  }

  async function handleDelete(id: string) {
    try {
      await deleteMedication(id)
      await refresh()
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось удалить запись.')
    }
  }

  return (
    <div>
      {error && <div className="error-banner">{error}</div>}

      <form className="stack" onSubmit={handleSubmit}>
        <input
          placeholder="Название препарата"
          value={form.name}
          onChange={(e) => setForm({ ...form, name: e.target.value })}
        />
        <input
          placeholder="Инструкция (необязательно)"
          value={form.instructions}
          onChange={(e) => setForm({ ...form, instructions: e.target.value })}
        />
        <input
          type="date"
          value={form.expiryDate}
          onChange={(e) => setForm({ ...form, expiryDate: e.target.value })}
        />
        <input
          type="number"
          min={0}
          placeholder="Количество"
          value={form.quantity}
          onChange={(e) => setForm({ ...form, quantity: Number(e.target.value) })}
        />
        <button className="primary" type="submit">
          {editingId ? 'Сохранить' : 'Добавить'}
        </button>
        {editingId && (
          <button
            type="button"
            className="secondary"
            onClick={() => {
              setEditingId(null)
              setForm(emptyForm)
            }}
          >
            Отмена
          </button>
        )}
      </form>

      {items.map((item) => (
        <div className="card" key={item.id}>
          <div className="row">
            <strong>{item.name}</strong>
            <span className="muted">кол-во: {item.quantity}</span>
          </div>
          {item.instructions && <p className="muted">{item.instructions}</p>}
          {item.expiryDate && <p className="muted">Срок годности: {item.expiryDate}</p>}
          <div className="row" style={{ marginTop: 6 }}>
            <button className="secondary" onClick={() => startEdit(item)}>
              Изменить
            </button>
            <button className="secondary danger" onClick={() => handleDelete(item.id)}>
              Удалить
            </button>
          </div>
        </div>
      ))}

      {items.length === 0 && <p className="muted">Аптечка пуста.</p>}
    </div>
  )
}

// src/FamilyHub.Web/src/app/components/medications-tab/medications-tab.component.ts
import { Component, Input, OnChanges, SimpleChanges, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, ApiError } from '../../services/api.service';
import type { Medication } from '../../models/types';

@Component({
  selector: 'app-medications-tab',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './medications-tab.component.html',
})
export class MedicationsTabComponent implements OnChanges {
  @Input() familyId!: string;

  private readonly api = inject(ApiService);

  items: Medication[] = [];
  form = { name: '', instructions: '', expiryDate: '', quantity: 1 };
  editingId: string | null = null;
  error: string | null = null;

  async ngOnChanges(changes: SimpleChanges): Promise<void> {
    if (changes['familyId']) {
      this.resetForm();
      await this.refresh();
    }
  }

  async refresh(): Promise<void> {
    try {
      this.items = await this.api.getMedications(this.familyId);
      this.error = null;
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось загрузить аптечку.';
    }
  }

  async handleSubmit(): Promise<void> {
    if (!this.form.name.trim()) return;
    const input = {
      name: this.form.name.trim(),
      instructions: this.form.instructions.trim() || null,
      expiryDate: this.form.expiryDate || null,
      quantity: Number(this.form.quantity) || 0,
    };
    try {
      if (this.editingId) {
        await this.api.updateMedication(this.editingId, input);
      } else {
        await this.api.createMedication(this.familyId, input);
      }
      this.resetForm();
      await this.refresh();
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось сохранить запись.';
    }
  }

  startEdit(item: Medication): void {
    this.editingId = item.id;
    this.form = {
      name: item.name,
      instructions: item.instructions ?? '',
      expiryDate: item.expiryDate ?? '',
      quantity: item.quantity,
    };
  }

  async handleDelete(id: string): Promise<void> {
    try {
      await this.api.deleteMedication(id);
      await this.refresh();
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось удалить запись.';
    }
  }

  resetForm(): void {
    this.form = { name: '', instructions: '', expiryDate: '', quantity: 1 };
    this.editingId = null;
  }
}

<div>
  @if (!state.activeFamilyId() && !state.loading()) {
    <p class="muted">
      Нет ни одной семьи, в которой вы состоите как активный участник.
      Создайте семью или примите инвайт на вкладке «Семьи».
    </p>
  } @else if (state.activeFamilyId()) {
    @if (error) {
      <div class="alert alert-danger py-2 mb-2">{{ error }}</div>
    }

    <div class="card mb-3">
      <div class="card-body p-3">
        <div class="d-flex flex-column gap-2">
          <input
            class="form-control form-control-sm"
            [(ngModel)]="form.name"
            placeholder="Название препарата"
          />
          <input
            class="form-control form-control-sm"
            [(ngModel)]="form.instructions"
            placeholder="Инструкция (необязательно)"
          />
          <input
            class="form-control form-control-sm"
            type="date"
            [(ngModel)]="form.expiryDate"
          />
          <input
            class="form-control form-control-sm"
            type="number"
            min="0"
            [(ngModel)]="form.quantity"
            placeholder="Количество"
          />
          <div class="d-flex gap-2">
            <button class="btn btn-primary btn-sm" (click)="handleSubmit()">
              {{ editingId ? 'Сохранить' : 'Добавить' }}
            </button>
            @if (editingId) {
              <button class="btn btn-outline-secondary btn-sm" (click)="resetForm()">Отмена</button>
            }
          </div>
        </div>
      </div>
    </div>

    @for (item of items; track item.id) {
      <div class="card mb-2">
        <div class="card-body p-3">
          <div class="d-flex justify-content-between align-items-center mb-1">
            <strong>{{ item.name }}</strong>
            <span class="muted">кол-во: {{ item.quantity }}</span>
          </div>
          @if (item.instructions) {
            <p class="muted mb-1">{{ item.instructions }}</p>
          }
          @if (item.expiryDate) {
            <p class="muted mb-2">Срок годности: {{ item.expiryDate }}</p>
          }
          <div class="d-flex gap-2">
            <button class="btn btn-outline-secondary btn-sm" (click)="startEdit(item)">Изменить</button>
            <button class="btn btn-outline-danger btn-sm" (click)="handleDelete(item.id)">Удалить</button>
          </div>
        </div>
      </div>
    }

    @if (items.length === 0) {
      <p class="muted">Аптечка пуста.</p>
    }
  }
</div>
