// src/FamilyHub.Web/src/components/MedicalRecordsTab.tsx
import { useEffect, useState, type FormEvent } from 'react'
import {
  ApiError,
  createMedicalRecord,
  getAttachmentUrl,
  getMedicalRecords,
  hideMedicalRecord,
  shareMedicalRecord,
  uploadAttachment,
  unhideMedicalRecord,
  unshareMedicalRecord,
} from '../api'
import type { Attachment, FamilySummary, MedicalRecord } from '../types'
import { openExternalLink } from '../telegram'

interface Props {
  activeFamilies: FamilySummary[]
}

const emptyForm = { personName: '', recordDate: '', doctor: '', description: '' }

export default function MedicalRecordsTab({ activeFamilies }: Props) {
  const [items, setItems] = useState<MedicalRecord[]>([])
  const [form, setForm] = useState(emptyForm)
  const [error, setError] = useState<string | null>(null)
  const [shareFamilyByRecord, setShareFamilyByRecord] = useState<Record<string, string>>({})
  // Бэкенд не отдаёт список вложений записи отдельным эндпоинтом — храним то, что
  // загрузили в текущей сессии (ответ POST .../attachments содержит Attachment целиком).
  const [attachmentsByRecord, setAttachmentsByRecord] = useState<Record<string, Attachment[]>>({})

  async function refresh() {
    try {
      setItems(await getMedicalRecords())
      setError(null)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось загрузить анализы.')
    }
  }

  useEffect(() => {
    refresh()
  }, [])

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (!form.personName.trim() || !form.recordDate) return
    try {
      await createMedicalRecord({
        personName: form.personName.trim(),
        recordDate: form.recordDate,
        doctor: form.doctor.trim() || null,
        description: form.description.trim() || null,
        hideFromFamilyIds: null,
      })
      setForm(emptyForm)
      await refresh()
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось сохранить запись.')
    }
  }

  async function handleUpload(recordId: string, file: File | null) {
    if (!file) return
    try {
      const attachment = await uploadAttachment(recordId, file)
      setAttachmentsByRecord((prev) => ({
        ...prev,
        [recordId]: [...(prev[recordId] ?? []), attachment],
      }))
      setError(null)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось загрузить файл.')
    }
  }

  async function handleOpenAttachment(attachmentId: string) {
    try {
      const { url } = await getAttachmentUrl(attachmentId)
      openExternalLink(url)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось получить ссылку на файл.')
    }
  }

  async function handleShare(recordId: string, share: boolean) {
    const familyId = shareFamilyByRecord[recordId]
    if (!familyId) return
    try {
      if (share) {
        await shareMedicalRecord(familyId)
      } else {
        await unshareMedicalRecord(familyId)
      }
      setError(null)
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : 'Действие доступно только владельцу записи.',
      )
    }
  }

  async function handleHide(recordId: string, hide: boolean) {
    const familyId = shareFamilyByRecord[recordId]
    if (!familyId) return
    try {
      if (hide) {
        await hideMedicalRecord(recordId, [familyId])
      } else {
        await unhideMedicalRecord(recordId, [familyId])
      }
      setError(null)
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : 'Действие доступно только владельцу записи.',
      )
    }
  }

  return (
    <div>
      {error && <div className="error-banner">{error}</div>}

      <form className="stack" onSubmit={handleSubmit}>
        <input
          placeholder="Пациент"
          value={form.personName}
          onChange={(e) => setForm({ ...form, personName: e.target.value })}
        />
        <input
          type="date"
          value={form.recordDate}
          onChange={(e) => setForm({ ...form, recordDate: e.target.value })}
        />
        <input
          placeholder="Врач (необязательно)"
          value={form.doctor}
          onChange={(e) => setForm({ ...form, doctor: e.target.value })}
        />
        <textarea
          placeholder="Описание (необязательно)"
          value={form.description}
          onChange={(e) => setForm({ ...form, description: e.target.value })}
        />
        <button className="primary" type="submit">
          Добавить запись
        </button>
      </form>

      {items.map((item) => (
        <div className="card" key={item.id}>
          <div className="row">
            <strong>{item.personName}</strong>
            <span className="muted">{item.recordDate}</span>
          </div>
          {item.doctor && <p className="muted">Врач: {item.doctor}</p>}
          {item.description && <p>{item.description}</p>}

          <div style={{ marginTop: 8 }}>
            <input type="file" onChange={(e) => handleUpload(item.id, e.target.files?.[0] ?? null)} />
          </div>

          {activeFamilies.length > 0 && (
            <div style={{ marginTop: 8 }}>
              <select
                value={shareFamilyByRecord[item.id] ?? ''}
                onChange={(e) =>
                  setShareFamilyByRecord((prev) => ({ ...prev, [item.id]: e.target.value }))
                }
              >
                <option value="">Выберите семью…</option>
                {activeFamilies.map((f) => (
                  <option key={f.id} value={f.id}>
                    {f.name}
                  </option>
                ))}
              </select>
              <div className="row" style={{ marginTop: 6 }}>
                <button className="secondary" onClick={() => handleShare(item.id, true)}>
                  Поделиться
                </button>
                <button className="secondary" onClick={() => handleShare(item.id, false)}>
                  Перестать делиться
                </button>
              </div>
              <div className="row" style={{ marginTop: 6 }}>
                <button className="secondary" onClick={() => handleHide(item.id, true)}>
                  Скрыть от семьи
                </button>
                <button className="secondary" onClick={() => handleHide(item.id, false)}>
                  Показать семье
                </button>
              </div>
            </div>
          )}

          {(attachmentsByRecord[item.id]?.length ?? 0) > 0 && (
            <ul style={{ marginTop: 8, paddingLeft: 18 }}>
              {attachmentsByRecord[item.id].map((a) => (
                <li key={a.id}>
                  <button className="secondary" onClick={() => handleOpenAttachment(a.id)}>
                    {a.fileName}
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      ))}

      {items.length === 0 && <p className="muted">Записей нет.</p>}
    </div>
  )
}

// src/FamilyHub.Web/src/app/components/medical-records-tab/medical-records-tab.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, ApiError } from '../../services/api.service';
import { TelegramService } from '../../services/telegram.service';
import { FamilyStateService } from '../../services/family-state.service';
import type { Attachment, MedicalRecord } from '../../models/types';

@Component({
  selector: 'app-medical-records-tab',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './medical-records-tab.component.html',
})
export class MedicalRecordsTabComponent implements OnInit {
  readonly state = inject(FamilyStateService);
  private readonly api = inject(ApiService);
  private readonly tg = inject(TelegramService);

  items: MedicalRecord[] = [];
  form = { personName: '', recordDate: '', doctor: '', description: '' };
  error: string | null = null;
  shareFamilyByRecord: Record<string, string> = {};
  // Бэкенд не отдаёт список вложений отдельным эндпоинтом — храним то, что
  // загрузили в текущей сессии (ответ POST .../attachments содержит Attachment целиком).
  attachmentsByRecord: Record<string, Attachment[]> = {};

  ngOnInit(): void {
    this.refresh();
  }

  async refresh(): Promise<void> {
    try {
      this.items = await this.api.getMedicalRecords();
      this.error = null;
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось загрузить анализы.';
    }
  }

  async handleSubmit(): Promise<void> {
    if (!this.form.personName.trim() || !this.form.recordDate) return;
    try {
      await this.api.createMedicalRecord({
        personName: this.form.personName.trim(),
        recordDate: this.form.recordDate,
        doctor: this.form.doctor.trim() || null,
        description: this.form.description.trim() || null,
        hideFromFamilyIds: null,
      });
      this.form = { personName: '', recordDate: '', doctor: '', description: '' };
      await this.refresh();
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось сохранить запись.';
    }
  }

  async handleUpload(recordId: string, event: Event): Promise<void> {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    try {
      const attachment = await this.api.uploadAttachment(recordId, file);
      this.attachmentsByRecord = {
        ...this.attachmentsByRecord,
        [recordId]: [...(this.attachmentsByRecord[recordId] ?? []), attachment],
      };
      this.error = null;
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось загрузить файл.';
    }
  }

  async handleOpenAttachment(attachmentId: string): Promise<void> {
    try {
      const { url } = await this.api.getAttachmentUrl(attachmentId);
      this.tg.openExternalLink(url);
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось получить ссылку на файл.';
    }
  }

  async handleShare(recordId: string, share: boolean): Promise<void> {
    const familyId = this.shareFamilyByRecord[recordId];
    if (!familyId) return;
    try {
      if (share) {
        await this.api.shareMedicalRecord(familyId);
      } else {
        await this.api.unshareMedicalRecord(familyId);
      }
      this.error = null;
    } catch (err) {
      this.error =
        err instanceof ApiError ? err.message : 'Действие доступно только владельцу записи.';
    }
  }

  async handleHide(recordId: string, hide: boolean): Promise<void> {
    const familyId = this.shareFamilyByRecord[recordId];
    if (!familyId) return;
    try {
      if (hide) {
        await this.api.hideMedicalRecord(recordId, [familyId]);
      } else {
        await this.api.unhideMedicalRecord(recordId, [familyId]);
      }
      this.error = null;
    } catch (err) {
      this.error =
        err instanceof ApiError ? err.message : 'Действие доступно только владельцу записи.';
    }
  }

  setShareFamily(recordId: string, familyId: string): void {
    this.shareFamilyByRecord = { ...this.shareFamilyByRecord, [recordId]: familyId };
  }

  attachmentsFor(recordId: string): Attachment[] {
    return this.attachmentsByRecord[recordId] ?? [];
  }

  shareFamilyFor(recordId: string): string {
    return this.shareFamilyByRecord[recordId] ?? '';
  }
}

<div>
  @if (error) {
    <div class="alert alert-danger py-2 mb-2">{{ error }}</div>
  }

  <div class="card mb-3">
    <div class="card-body p-3">
      <div class="d-flex flex-column gap-2">
        <input
          class="form-control form-control-sm"
          [(ngModel)]="form.personName"
          placeholder="Пациент"
        />
        <input
          class="form-control form-control-sm"
          type="date"
          [(ngModel)]="form.recordDate"
        />
        <input
          class="form-control form-control-sm"
          [(ngModel)]="form.doctor"
          placeholder="Врач (необязательно)"
        />
        <textarea
          class="form-control form-control-sm"
          [(ngModel)]="form.description"
          placeholder="Описание (необязательно)"
          rows="2"
        ></textarea>
        <button class="btn btn-primary btn-sm" (click)="handleSubmit()">Добавить запись</button>
      </div>
    </div>
  </div>

  @for (item of items; track item.id) {
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="d-flex justify-content-between align-items-center mb-1">
          <strong>{{ item.personName }}</strong>
          <span class="muted">{{ item.recordDate }}</span>
        </div>
        @if (item.doctor) {
          <p class="muted mb-1">Врач: {{ item.doctor }}</p>
        }
        @if (item.description) {
          <p class="mb-2">{{ item.description }}</p>
        }

        <div class="mb-2">
          <input
            class="form-control form-control-sm"
            type="file"
            (change)="handleUpload(item.id, $event)"
          />
        </div>

        @if (state.activeFamilies().length > 0) {
          <div class="mb-1">
            <select
              class="form-select form-select-sm mb-2"
              [value]="shareFamilyFor(item.id)"
              (change)="setShareFamily(item.id, $any($event.target).value)"
            >
              <option value="">Выберите семью…</option>
              @for (f of state.activeFamilies(); track f.id) {
                <option [value]="f.id">{{ f.name }}</option>
              }
            </select>
            <div class="d-flex flex-wrap gap-1">
              <button class="btn btn-outline-secondary btn-sm" (click)="handleShare(item.id, true)">
                Поделиться
              </button>
              <button class="btn btn-outline-secondary btn-sm" (click)="handleShare(item.id, false)">
                Отменить доступ
              </button>
              <button class="btn btn-outline-secondary btn-sm" (click)="handleHide(item.id, true)">
                Скрыть
              </button>
              <button class="btn btn-outline-secondary btn-sm" (click)="handleHide(item.id, false)">
                Показать
              </button>
            </div>
          </div>
        }

        @if (attachmentsFor(item.id).length > 0) {
          <ul class="list-unstyled mt-2 mb-0">
            @for (a of attachmentsFor(item.id); track a.id) {
              <li>
                <button class="btn btn-link btn-sm p-0" (click)="handleOpenAttachment(a.id)">
                  {{ a.fileName }}
                </button>
              </li>
            }
          </ul>
        }
      </div>
    </div>
  }

  @if (items.length === 0) {
    <p class="muted">Записей нет.</p>
  }
</div>
