// src/FamilyHub.Web/src/components/BirthdaysTab.tsx
import { useEffect, useState, type FormEvent } from 'react'
import { ApiError, createBirthday, deleteBirthday, getBirthdays, updateBirthday } from '../api'
import type { Birthday } from '../types'

interface Props {
  familyId: string
}

const emptyForm = { personName: '', date: '' }

export default function BirthdaysTab({ familyId }: Props) {
  const [items, setItems] = useState<Birthday[]>([])
  const [form, setForm] = useState(emptyForm)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function refresh() {
    try {
      setItems(await getBirthdays(familyId))
      setError(null)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось загрузить дни рождения.')
    }
  }

  useEffect(() => {
    refresh()
    setForm(emptyForm)
    setEditingId(null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [familyId])

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (!form.personName.trim() || !form.date) return
    const input = { personName: form.personName.trim(), date: form.date }
    try {
      if (editingId) {
        await updateBirthday(editingId, input)
      } else {
        await createBirthday(familyId, input)
      }
      setForm(emptyForm)
      setEditingId(null)
      await refresh()
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось сохранить запись.')
    }
  }

  function startEdit(item: Birthday) {
    setEditingId(item.id)
    setForm({ personName: item.personName, date: item.date })
  }

  async function handleDelete(id: string) {
    try {
      await deleteBirthday(id)
      await refresh()
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Не удалось удалить запись.')
    }
  }

  return (
    <div>
      {error && <div className="error-banner">{error}</div>}

      <form className="stack" onSubmit={handleSubmit}>
        <input
          placeholder="Имя"
          value={form.personName}
          onChange={(e) => setForm({ ...form, personName: e.target.value })}
        />
        <input
          type="date"
          value={form.date}
          onChange={(e) => setForm({ ...form, date: e.target.value })}
        />
        <button className="primary" type="submit">
          {editingId ? 'Сохранить' : 'Добавить'}
        </button>
        {editingId && (
          <button
            type="button"
            className="secondary"
            onClick={() => {
              setEditingId(null)
              setForm(emptyForm)
            }}
          >
            Отмена
          </button>
        )}
      </form>

      {items.map((item) => (
        <div className="card" key={item.id}>
          <div className="row">
            <strong>{item.personName}</strong>
            <span className="muted">{item.date}</span>
          </div>
          <div className="row" style={{ marginTop: 6 }}>
            <button className="secondary" onClick={() => startEdit(item)}>
              Изменить
            </button>
            <button className="secondary danger" onClick={() => handleDelete(item.id)}>
              Удалить
            </button>
          </div>
        </div>
      ))}

      {items.length === 0 && <p className="muted">Дни рождения не добавлены.</p>}
    </div>
  )
}

// src/FamilyHub.Web/src/app/components/birthdays-tab/birthdays-tab.component.ts
import { Component, Input, OnChanges, SimpleChanges, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, ApiError } from '../../services/api.service';
import type { Birthday } from '../../models/types';

@Component({
  selector: 'app-birthdays-tab',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './birthdays-tab.component.html',
})
export class BirthdaysTabComponent implements OnChanges {
  @Input() familyId!: string;

  private readonly api = inject(ApiService);

  items: Birthday[] = [];
  form = { personName: '', date: '' };
  editingId: string | null = null;
  error: string | null = null;

  async ngOnChanges(changes: SimpleChanges): Promise<void> {
    if (changes['familyId']) {
      this.resetForm();
      await this.refresh();
    }
  }

  async refresh(): Promise<void> {
    try {
      this.items = await this.api.getBirthdays(this.familyId);
      this.error = null;
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось загрузить дни рождения.';
    }
  }

  async handleSubmit(): Promise<void> {
    if (!this.form.personName.trim() || !this.form.date) return;
    const input = { personName: this.form.personName.trim(), date: this.form.date };
    try {
      if (this.editingId) {
        await this.api.updateBirthday(this.editingId, input);
      } else {
        await this.api.createBirthday(this.familyId, input);
      }
      this.resetForm();
      await this.refresh();
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось сохранить запись.';
    }
  }

  startEdit(item: Birthday): void {
    this.editingId = item.id;
    this.form = { personName: item.personName, date: item.date };
  }

  async handleDelete(id: string): Promise<void> {
    try {
      await this.api.deleteBirthday(id);
      await this.refresh();
    } catch (err) {
      this.error = err instanceof ApiError ? err.message : 'Не удалось удалить запись.';
    }
  }

  resetForm(): void {
    this.form = { personName: '', date: '' };
    this.editingId = null;
  }
}

<div>
  @if (error) {
    <div class="alert alert-danger py-2 mb-2">{{ error }}</div>
  }

  <div class="card mb-3">
    <div class="card-body p-3">
      <div class="d-flex flex-column gap-2">
        <input
          class="form-control form-control-sm"
          [(ngModel)]="form.personName"
          placeholder="Имя"
        />
        <input
          class="form-control form-control-sm"
          type="date"
          [(ngModel)]="form.date"
        />
        <div class="d-flex gap-2">
          <button class="btn btn-primary btn-sm" (click)="handleSubmit()">
            {{ editingId ? 'Сохранить' : 'Добавить' }}
          </button>
          @if (editingId) {
            <button class="btn btn-outline-secondary btn-sm" (click)="resetForm()">Отмена</button>
          }
        </div>
      </div>
    </div>
  </div>

  @for (item of items; track item.id) {
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="d-flex justify-content-between align-items-center mb-2">
          <strong>{{ item.personName }}</strong>
          <span class="muted">{{ item.date }}</span>
        </div>
        <div class="d-flex gap-2">
          <button class="btn btn-outline-secondary btn-sm" (click)="startEdit(item)">Изменить</button>
          <button class="btn btn-outline-danger btn-sm" (click)="handleDelete(item.id)">Удалить</button>
        </div>
      </div>
    </div>
  }

  @if (items.length === 0) {
    <p class="muted">Дни рождения не добавлены.</p>
  }
</div>
